[package]
name = "reminder_rs"
version = "1.4.0"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
# chrono-english = "0.1.4"
tokio = { version = "1.0", features = ["process"] }
reqwest = { version = "0.11", features = ["rustls-tls"] }
regex = "1.4"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4"
num-integer = "0.1"
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
rand = "0.7"
Inflector = "0.11"
levenshtein = "1.0"

[dependencies.sqlx]
git = "https://github.com/ant32/sqlx"
default-features = false
features = ["runtime-tokio-rustls", "macros", "mysql", "bigdecimal", "chrono"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["builder", "client", "framework", "cache", "gateway", "http", "model", "utils", "collector", "rustls_backend"]

[dependencies.regex_command_attr]
path = "./regex_command_attr"
