[package]
name = "reminder_rs"
version = "0.1.0"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
serenity = { version = "0.9.0-rc.2", features = ["collector"] }
dotenv = "0.15"
tokio = { version = "0.2.19", features = ["process"] }
reqwest = "0.10.6"
sqlx = { version = "0.3.5", default-features = false, features = ["runtime-tokio", "macros", "mysql", "bigdecimal", "chrono"] }
regex = "1.3.9"
async-trait = "0.1.36"
log = "0.4.11"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4.0"
num-integer = "0.1.43"
num-traits = "0.2.12"
custom_error = "1.7.1"
serde = "1.0.115"
serde_json = "1.0.57"
rand = "0.7.3"
Inflector = "0.11.4"

[dependencies.regex_command_attr]
path = "./regex_command_attr"
