[package]
name = "reminder_rs"
version = "1.3.5"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
tokio = { version = "0.2", features = ["process"] }
reqwest = { version = "0.10", features = ["rustls-tls"] }
sqlx = { version = "0.4", default-features = false, features = ["runtime-tokio-rustls", "macros", "mysql", "bigdecimal", "chrono"] }
regex = "1.4"
async-trait = "0.1"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4"
num-integer = "0.1"
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
rand = "0.7"
Inflector = "0.11"
levenshtein = "1.0"

[dependencies.serenity]
git = "https://github.com/jellywx/serenity"
branch = "jellywx-member_permissions"
default-features = false
features = ["builder", "client", "framework", "cache", "gateway", "http", "model", "utils", "rustls_backend", "collector"]

[dependencies.regex_command_attr]
path = "./regex_command_attr"
