[package]
name = "reminder_rs"
version = "1.5.1"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
dashmap = "4.0"
dotenv = "0.15"
humantime = "2.1"
tokio = { version = "1", features = ["process", "full"] }
reqwest = "0.11"
regex = "1.4"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4"
num-integer = "0.1"
serde = "1.0"
serde_json = "1.0"
rand = "0.7"
levenshtein = "1.0"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", features = ["collector", "unstable_discord_api"] }
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "macros", "mysql", "bigdecimal", "chrono"]}
ring = "0.16"
base64 = "0.13.0"

[dependencies.regex_command_attr]
path = "./regex_command_attr"
